name: opensubtitles_api
description: "A Dart package for working with the OpenSubtitles API. This package provides a simple interface for interacting with the OpenSubtitles API, including subtitle search, download, authentication, and other features."
version: 0.0.1
homepage: https://github.com/Farg0k/opensubtitles_api
repository: https://github.com/Farg0k/opensubtitles_api
license: MIT
environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^5.1.1